### ISSUE TITLE
Inquiry about Open Source Plans for LogiCode

### ISSUE THREAD

**Issue by zhiqing0205** [22strongestme/LOCO-Annotations#1]
I'm really interested in your project, especially the image API part. Just wondering if you have any plans to open source it? Would love to dive into the code and maybe contribute.

**Comment by 22strongestme** [comment]
> I'm really interested in your project, especially the image API part. Just wondering if you have any plans to open source it? Would love to dive into the code and maybe contribute.

Hi zhiqing0205,

Thank you for your interest in our project! Currently, we do not have immediate plans to open source the project. However, we do recognize the value of open source and are considering it for the future. Once we have the time to properly organize the code, we will open source it.
