### ISSUE TITLE
Query about Fine-grained Annotation Process for Legacy Dataset

### ISSUE THREAD

**Issue by zhiqing0205** [22strongestme/LOCO-Annotations#2]
Hello,
I noticed that you have provided fine-grained annotations for the previous legacy dataset in this project. I'm very interested in understanding the process you used for this annotation. Specifically:

- 1 What methodology did you employ for the fine-grained annotation?
- 2 Were there specific tools or software used in the annotation process?
- 3 How did you ensure consistency and accuracy in the annotations?
- 4 Were there any challenges you encountered when annotating the legacy data, and how did you overcome them?
- 5 Is there any documentation available that outlines your annotation guidelines or process?

Understanding your approach would be extremely valuable for my own work and potentially for others in the community. Any insights you can provide would be greatly appreciated.
Thank you for your time and for your contributions to this project.
Best regards,
zhiqing0205

**Comment by 22strongestme** [comment]
> Hello, I noticed that you have provided fine-grained annotations for the previous legacy dataset in this project. I'm very interested in understanding the process you used for this annotation. Specifically:
> 
> * 1 What methodology did you employ for the fine-grained annotation?
> * 2 Were there specific tools or software used in the annotation process?
> * 3 How did you ensure consistency and accuracy in the annotations?
> * 4 Were there any challenges you encountered when annotating the legacy data, and how did you overcome them?
> * 5 Is there any documentation available that outlines your annotation guidelines or process?
> 
> Understanding your approach would be extremely valuable for my own work and potentially for others in the community. Any insights you can provide would be greatly appreciated. Thank you for your time and for your contributions to this project. Best regards, zhiqing0205

Hi zhiqing0205,

Thank you for your interest in our project and for your thoughtful questions. I'm happy to provide some insights into our annotation process for the dataset. Here are the answers to your specific queries:

Methodology Employed for Fine-Grained Annotation:
We utilized a combination of automated and manual methods for fine-grained annotation. Specifically, we used the AnyLabeling tool, which you can find on GitHub here, to handle the majority of the initial labeling process.

Tools or Software Used in the Annotation Process:
For the initial segmentation, we employed the Segment Anything Model (SAM) to perform the preliminary segmentation. This allowed us to quickly generate rough annotations, which we then manually reviewed and refined using AnyLabeling. The combination of these tools significantly streamlined the process, although it still required substantial manual effort.

Ensuring Consistency and Accuracy in Annotations:
To ensure consistency and accuracy, we implemented a multi-step verification process. After the initial automated segmentation with SAM, each annotation was carefully reviewed and adjusted by a team of annotators.

Challenges Encountered and How We Overcame Them:
One of the primary challenges we faced was the sheer volume of data that needed to be annotated. The automated tools helped reduce the workload, but manual verification was still essential to ensure high-quality annotations. We overcame this challenge by organizing the annotation process into manageable batches and ensuring clear communication and collaboration among the team members.

Documentation of Annotation Guidelines or Process:
We currently do not have formal documentation outlining our annotation guidelines and process. However, if there is sufficient interest, we can consider creating and sharing these documents to help others in the community.

**Comment by tz3458172** [comment]
Hello, I noticed that the Code Generation in your paper utilizes image processing APIs, but there is no description of how these APIs are structured. I'm curious to know if these APIs incorporate small models for image processing tasks like segmentation and object detection.

**Comment by 22strongestme** [comment]
> Hello, I noticed that the Code Generation in your paper utilizes image processing APIs, but there is no description of how these APIs are structured. I'm curious to know if these APIs incorporate small models for image processing tasks like segmentation and object detection.

Thanks for your question! In my framework, some image processing APIs are used to complete the task. These APIs are not directly embedded in small models for segmentation or object detection, but process image features through logic based on predefined rules. For example, the color matching function is processed through the HSV color space to ensure consistency，the object detection part relies on the annotation information in the LOCO-Annotations file.The framework relies more on the logical code to interpret the data, extract key visual elements (such as size, color, position) through these APIs, and then combine logical rules for anomaly detection.
The main reason is that these models cannot be used directly in the industrial field. In the future, we can consider making industry-specific APIs.
